# Generated by Django 4.1.1 on 2022-09-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(default='', max_length=111),
        ),
    ]
